name: Trigger auto deployment for ca-mcppostgresql-cac-prd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ca-mcppostgresql-cac-prd-AutoDeployTrigger-5ea733e9-58ba-4bbb-8588-fc0288a90ac1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CAMCPPOSTGRESQLCACPRD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAMCPPOSTGRESQLCACPRD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAMCPPOSTGRESQLCACPRD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrjarviscacprd.azurecr.io
          registryUsername: ${{ secrets.CAMCPPOSTGRESQLCACPRD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAMCPPOSTGRESQLCACPRD_REGISTRY_PASSWORD }}
          containerAppName: ca-mcppostgresql-cac-prd
          resourceGroup: rg-Jarvis-cae-prd
          imageToBuild: acrjarviscacprd.azurecr.io/ca-mcppostgresql-cac-prd:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


